- name: Is running
  shell: "/usr/local/bin/consul agent {{ consul_extra }} \  
    -ui-dir /data/consul/ui \
    -data-dir /data/consul/data \
    -config-dir /data/consul/config \
    -node={{ ansible_hostname }} \
     -bind={{ ansible_enp0s8.ipv4.address }} \
    -client=0.0.0.0 \
    >{{ logs_dir }}/consul.log   &" 
  tags: [consul]

- name: Has joined
  shell: "/usr/local/bin/consul join {{ consul_server_ip }} "
  when: consul_server_ip is defined
  tags: [consul]