- name:  Setting virtual memory
  shell: sysctl -w vm.max_map_count=262144
  tags:  [elasticsearch]


- name: Container is running
  docker:
    name: elasticsearch
    image: elasticsearch
    state: running
    ports:
      - 9200:9200
    volumes:
      /data/elasticsearch:/usr/share/elasticsearch/data
  tags: [elasticsearch]
