file: path=/etc/docker state=directory mode=0755

docker_extra: ""

centos_files: [
  { src: "docker.centos.repo", dest: "/etc/yum.repos.d/docker.repo" },
  { src: "docker.centos.service", dest: "/lib/systemd/system/docker.service" },
  { src: "daemon.json", dest: "/etc/docker/daemon.json" },
]
