- name: Directories are created
  file:
    path: "{{ item }}"
    state: directory
  with_items: directories
  tags: [consul]

- name: Files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: files
  register: files
  tags: [consul]


- name: Templates are present
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: templates
  register: templates
  tags: [consul]

- name: Is running
  shell: "/usr/local/bin/consul agent {{ consul_extra }} \  
    -ui-dir /data/consul/ui \
    -data-dir /data/consul/data \
    -config-dir /data/consul/config \
    -node={{ ansible_hostname }} \
    -bind={{ ansible_eth1.ipv4.address }} \
    -client=0.0.0.0 \
    >{{ logs_dir }}/consul.log   &" 
  tags: [consul]

- name: Has joined
  shell: consul join {{ consul_server_ip }}
  when: consul_server_ip is defined
  tags: [consul]

- name: Consul is restarted
  shell: killall -HUP consul
  when: files|changed or templates|changed
  tags: [consul]
